// src/components/Footer.svelte
<script lang="ts">
	import Logo from './Logo.svelte';
	import XLogo from 'phosphor-svelte/lib/XLogo';
	import GithubLogo from 'phosphor-svelte/lib/GithubLogo';
	import LinkedinLogo from 'phosphor-svelte/lib/LinkedinLogo';

	const CONTACT_US_EMAIL = import.meta.env.VITE_CONTACT_US_EMAIL || '';
</script>

<footer class="text-white">
	<div class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8">
		<div class="grid grid-cols-1 gap-12 md:grid-cols-4">
			<div class="col-span-1 md:col-span-2">
				<Logo />
				<p class="text-sSlate-300 mt-6 mb-8 max-w-md text-lg leading-relaxed">
					Pioneering intelligent systems that transform ideas into reality. Building the future, one
					innovation at a time.
				</p>
				<div class="flex space-x-6">
					<a
						href="https://x.com/ASIMOV_Protocol"
						class="text-sSlate-300 hover:text-oOrange-500 transition-colors duration-200"
						target="_blank"
					>
						<span class="sr-only">Twitter</span>
						<XLogo size={28} />
					</a>
					<a
						href="https://github.com/asimov-platform"
						class="text-sSlate-300 hover:text-oOrange-500 transition-colors duration-200"
						target="_blank"
					>
						<span class="sr-only">GitHub</span>
						<GithubLogo size={28} />
					</a>
					<a
						href="https://www.linkedin.com/company/asimov-protocol"
						class="text-sSlate-300 hover:text-oOrange-500 transition-colors duration-200"
						target="_blank"
					>
						<span class="sr-only">LinkedIn</span>
						<LinkedinLogo size={28} />
					</a>
				</div>
			</div>

			<div>
				<h3 class="mb-6 text-xl font-semibold text-white">Quick Links</h3>
				<ul class="space-y-3">
					<li>
						<a
							href="https://www.asimovprotocol.org/about"
							class="text-sSlate-300 hover:text-oOrange-500 text-lg transition-colors duration-200"
							target="_blank"
							>About</a
						>
					</li>
					<li>
						<a
							href="https://github.com/asimov-platform"
							class="text-sSlate-300 hover:text-oOrange-500 text-lg transition-colors duration-200"
							target="_blank"
							>Projects</a
						>
					</li>
				</ul>
			</div>

			<div>
				<h3 class="mb-6 text-xl font-semibold text-white">Contact</h3>
				<ul class="text-sSlate-300 space-y-3 text-lg">
					<li>
						<a href="mailto:{CONTACT_US_EMAIL}" class="hover:text-oOrange-500 transition-colors duration-200">
							{CONTACT_US_EMAIL}
						</a>
					</li>
					<li class="hover:text-oOrange-500 transition-colors duration-200">
						599 Fairchild Dr, Mountain View, CA 94043
					</li>
				</ul>
			</div>
		</div>

		<div class="border-sSlate-800 mt-12 border-t pt-8">
			<div class="flex flex-col items-center justify-between md:flex-row">
				<p class="text-sSlate-300 text-base">© 2025 ASIMOV.Systems. All rights reserved.</p>
			</div>
		</div>
	</div>
</footer>

// src/components/Footer.tsx
import { Logo, LogoImage } from '@/components/shadcnblocks/logo';

interface MenuItem {
  title: string;
  links: {
    text: string;
    url: string;
    target?: string;
  }[];
}

interface FooterProps {
  logo?: {
    url: string;
    src: string;
    alt: string;
  };
  tagline?: string;
  menuItems?: MenuItem[];
  copyright?: string;
  bottomLinks?: {
    text: string;
    url: string;
  }[];
}

const Footer = ({
  logo = {
    src: '/logo.svg',
    alt: 'ASIMOV.SYSTEMS logo',
    url: '/'
  },
  tagline = '#BuildOnTruth',
  menuItems = [
    {
      title: 'Product',
      links: [
        { text: 'Overview', url: 'https://getasimov.ai', target: '_blank' },
        // { text: 'Pricing', url: '#' },
        // { text: 'Marketplace', url: '#' },
        // { text: 'Features', url: '#' },
        // { text: 'Integrations', url: '#' },
        // { text: 'Pricing', url: '#' }
      ]
    },
    {
      title: 'Company',
      links: [
        { text: 'About', url: 'https://www.asimovprotocol.org/about', target: '_blank' },
        // { text: 'Team', url: '#' },
        { text: 'Blog', url: 'https://asimov.blog', target: '_blank' },
        // { text: 'Careers', url: '#' },
        { text: 'Contact', url: '/contact' },
        // { text: 'Privacy', url: '#' }
      ]
    },
    {
      title: 'Resources',
      links: [
        { text: 'Docs', url: 'https://asimov-specs.github.io', target: '_blank' },
        // { text: 'Sales', url: '#' },
        // { text: 'Advertise', url: '#' }
      ]
    },
    {
      title: 'Social',
      links: [
        { text: 'Twitter', url: 'https://x.com/ASIMOV_Protocol', target: '_blank' },
        { text: 'GitHub', url: 'https://github.com/asimov-platform', target: '_blank' },
        { text: 'LinkedIn', url: 'https://www.linkedin.com/company/asimov-protocol', target: '_blank' }
      ]
    }
  ],
  copyright = '© 2025 ASIMOV Systems Inc.',
  // bottomLinks = [
  //   { text: 'Terms and Conditions', url: '#' },
  //   { text: 'Privacy Policy', url: '#' }
  // ]
}: FooterProps) => {
  return (
    <section className="py-32">
      <div className="container mx-auto px-4 lg:px-6">
        <footer>
          <div className="grid grid-cols-2 gap-8 lg:grid-cols-6">
            <div className="col-span-2 mb-8 lg:mb-0">
              <div className="flex items-center gap-2 lg:justify-start">
                <Logo url="/">
                  <LogoImage src={logo.src} alt={logo.alt} className="h-10" />
                </Logo>
              </div>
              <p className="mt-4 font-bold">{tagline}</p>
            </div>
            {menuItems.map((section, sectionIdx) => (
              <div key={sectionIdx}>
                <h3 className="mb-4 font-bold">{section.title}</h3>
                <ul className="text-muted-foreground space-y-4">
                  {section.links.map((link, linkIdx) => (
                    <li key={linkIdx} className="hover:text-primary font-medium">
                      <a href={link.url} target={link.target}>{link.text}</a>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
          <div className="text-muted-foreground mt-24 flex flex-col justify-between gap-4 border-t pt-8 text-sm font-medium md:flex-row md:items-center">
            <p>{copyright}</p>
            {/* <ul className="flex gap-4">
              {bottomLinks.map((link, linkIdx) => (
                <li key={linkIdx} className="hover:text-primary underline">
                  <a href={link.url}>{link.text}</a>
                </li>
              ))}
            </ul> */}
          </div>
        </footer>
      </div>
    </section>
  );
};

export { Footer };
